repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: local
  hooks:
  - id: vale
    name: vale
    entry: vale
    description: Run vale on your text
    types: [file, markdown]
    language: system
      # - repo: https://github.com/errata-ai/vale
      #   rev: v2.29.5
      #   hooks:
      #   - id: vale
