#!/usr/bin/env bash

python3 replace-on-build.py
bash copy-metrics-md

echo "testtest123"
echo  -n $ALGOLIA_APP_ID | base64
echo $PATH
echo "testtest1234"
# node scripts/update-vulnerability-categories.js