#!/usr/bin/env bash

python3 replace-on-build.py
bash copy-metrics-md
# commenting out for now just incase this leads to issues, requires manual call to update-vulnerability-categories.js
# node scripts/update-vulnerability-categories.js