#!/usr/bin/env python3
# /// script
# requires-python = ">=3.9"
# dependencies = ["pyyaml"]
#
# [tool.uv]
# exclude-newer = "1 week"
# ///
#
# Rebuild the API tab's endpoint navigation in docs.json from an OpenAPI spec.
#
# Why this exists: Mintlify can autogenerate a nav group per tag from a spec,
# and that is what this replaces. Autogenerated groups cannot carry a `root`
# page, so clicking a service in the sidebar opens whichever endpoint happens
# to sort first rather than a page describing the service. `root` is only
# available on an explicitly declared group -- which means the endpoint list
# has to be enumerated, which means it has to be generated.
#
# One group per tag, in the spec's own order (sort_openapi_nav.py has already
# put that in display-name order):
#
#   {
#     "group": "Issues",                                  <- x-displayName
#     "root": "api-reference/v2/services/issues",         <- landing page
#     "openapi": "public_v2.openapi.yaml",
#     "pages": ["GET /api/issues", ...]                    <- METHOD /path
#   }
#
# `root` is emitted only when a landing page for that service actually exists
# on disk, so a tag with no page still gets a working group.
#
# Runs in update-openapi-specs.yml after the spec is fetched, so a newly
# published endpoint appears in the nav in the same PR that adds it.

from __future__ import annotations

import argparse
import json
import pathlib
import re
import sys
from typing import Optional

import yaml

HTTP_METHODS = ("get", "post", "put", "patch", "delete", "options", "head", "trace")


def service_groups(spec: dict, docs_root: pathlib.Path, spec_name: str,
                   landing_dir: str) -> list[dict]:
    """One nav group per tag, each with its endpoints and its landing page."""
    display = {}
    for tag in spec.get("tags") or []:
        display[tag["name"]] = tag.get("x-displayName") or tag["name"]

    # tag -> ["GET /path", ...], in the order the spec lists paths
    endpoints: dict[str, list[str]] = {}
    for path, item in (spec.get("paths") or {}).items():
        if not isinstance(item, dict):
            continue
        for method, op in item.items():
            if method not in HTTP_METHODS or not isinstance(op, dict):
                continue
            tags = op.get("tags") or []
            if not tags:
                continue
            endpoints.setdefault(tags[0], []).append(f"{method.upper()} {path}")

    groups = []
    for tag, pages in endpoints.items():
        label = display.get(tag, tag)
        group: dict = {"group": label, "openapi": spec_name}
        # slug the display name the way the landing pages are named
        slug = re.sub(r"[^a-z0-9]+", "-", label.lower()).strip("-")
        landing = f"{landing_dir}/{slug}"
        if (docs_root / f"{landing}.mdx").exists():
            group["root"] = landing
        group["pages"] = pages
        groups.append(group)
    return groups


def replace_groups(docs: dict, dropdown: str, groups: list[dict],
                   keep: tuple[str, ...]) -> dict:
    """Swap the endpoint groups of one dropdown, keeping the named ones."""
    api = next(t for t in docs["navigation"]["tabs"] if t.get("tab") == "API")
    dd = next(d for d in api["dropdowns"] if d["dropdown"] == dropdown)
    dd["groups"] = [g for g in dd["groups"] if g.get("group") in keep] + groups
    return docs


def main(argv: Optional[list[str]] = None) -> int:
    parser = argparse.ArgumentParser(
        description="Rebuild the API tab endpoint navigation from an OpenAPI spec."
    )
    parser.add_argument("spec", help="path to the OpenAPI spec")
    parser.add_argument("docs_json", help="path to docs.json")
    parser.add_argument("--dropdown", required=True, help='e.g. "v2"')
    parser.add_argument(
        "--landing-dir", required=True,
        help="docs-relative dir holding the service pages, e.g. api-reference/v2/services",
    )
    parser.add_argument(
        "--keep", default="Overview",
        help="comma-separated groups to preserve ahead of the generated ones",
    )
    args = parser.parse_args(argv)

    docs_path = pathlib.Path(args.docs_json)
    docs_root = docs_path.parent
    spec = yaml.safe_load(pathlib.Path(args.spec).read_text())

    groups = service_groups(
        spec, docs_root, pathlib.Path(args.spec).name, args.landing_dir
    )
    if not groups:
        print(f"{args.spec}: no tagged operations, nav left alone")
        return 0

    docs = json.loads(docs_path.read_text())
    docs = replace_groups(docs, args.dropdown, groups, tuple(
        g.strip() for g in args.keep.split(",") if g.strip()
    ))
    docs_path.write_text(json.dumps(docs, indent=2, ensure_ascii=False) + "\n")

    rooted = sum(1 for g in groups if "root" in g)
    total = sum(len(g["pages"]) for g in groups)
    print(f"{docs_path}: {len(groups)} service groups, {rooted} with a landing page, "
          f"{total} endpoints")
    for g in groups:
        mark = "" if "root" in g else "   (no landing page)"
        print(f"    {len(g['pages']):4}  {g['group']}{mark}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
