#!/usr/bin/env python3
# /// script
# requires-python = ">=3.9"
# dependencies = ["pyyaml"]
#
# [tool.uv]
# exclude-newer = "1 week"
# ///
#
# Generate the endpoint table each service landing page shows.
#
# Why this exists: a service page needs to list the endpoints in that service,
# linked to their reference pages, and that list changes every time an endpoint
# is published, renamed or regrouped. Hand-maintaining it guarantees it goes
# stale, and a hardcoded "no endpoints yet" placeholder is wrong the moment the
# first one lands.
#
# One snippet per service, imported by the landing page, so the prose stays
# hand-written and the table stays correct. Rendered from the same spec the
# reference pages are generated from, in the sync workflow, so the two cannot
# disagree.
#
# Endpoint URLs come from generate_api_changelog rather than a second copy of
# the slug rules -- those were reverse-engineered against the rendered site and
# two copies would drift into broken links.

from __future__ import annotations

import argparse
import pathlib
import re
import sys
from typing import Optional

import yaml

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from generate_api_changelog import (  # noqa: E402
    METHOD_BADGE_COLORS,
    endpoint_urls,
    escape_mdx,
    mintlify_slug,
)

HTTP_METHODS = ("get", "post", "put", "patch", "delete", "options", "head", "trace")

HEADER = """{{/* Auto-generated by scripts/generate_service_endpoints.py -- do not edit by hand. */}}

{body}
"""

EMPTY = (
    "No endpoints are published in this service yet. They appear here as each one\n"
    "is published, and every change is recorded in the\n"
    "[changelog]({changelog})."
)


def first_sentence(text: str) -> str:
    """The lead sentence of a description, for a one-line table cell.

    Descriptions run to several paragraphs and carry Markdown of their own; a
    landing page wants the gist, with the endpoint page one click away.
    """
    text = " ".join((text or "").split())
    if not text:
        return ""
    # ". " is not a sentence end inside e.g. "v1. 2" or an abbreviation we care
    # about here, so accept the first period followed by a space and a capital.
    m = re.search(r"\.(?=\s+[A-Z(])", text)
    out = text[: m.start() + 1] if m else text
    return out if out.endswith(".") or not m else out


def service_tables(spec: dict, link_base: str) -> dict[str, str]:
    """display name -> the MDX table of that service's endpoints."""
    display = {
        t["name"]: (t.get("x-displayName") or t["name"]) for t in (spec.get("tags") or [])
    }
    urls = endpoint_urls(spec, link_base)

    rows: dict[str, list[str]] = {}
    for path, item in (spec.get("paths") or {}).items():
        if not isinstance(item, dict):
            continue
        for method, op in item.items():
            if method not in HTTP_METHODS or not isinstance(op, dict):
                continue
            tags = op.get("tags") or []
            if not tags:
                continue
            label = display.get(tags[0], tags[0])
            verb = method.upper()
            colour = METHOD_BADGE_COLORS.get(verb, "gray")
            title = op.get("summary") or f"{verb} {path}"
            url = urls.get((verb, path))
            linked = f"[{escape_mdx(title)}]({url})" if url else escape_mdx(title)
            desc = escape_mdx(first_sentence(op.get("description") or ""))
            badge = f'<Badge color="{colour}" size="sm">{verb}</Badge>'
            rows.setdefault(label, []).append(f"| {badge} {linked} | {desc} |")

    out = {}
    for label, body in rows.items():
        out[label] = "\n".join(
            ["| Endpoint | Description |", "| --- | --- |", *body]
        )
    return out


def main(argv: Optional[list[str]] = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate the endpoint table for each service landing page."
    )
    parser.add_argument("spec", help="path to the OpenAPI spec")
    parser.add_argument("out_dir", help="directory to write the snippets into")
    parser.add_argument("--link-base", required=True, help="e.g. /api-reference/v2")
    parser.add_argument(
        "--changelog", required=True, help="changelog page path, for the empty state"
    )
    parser.add_argument(
        "--services-dir", required=True,
        help="landing-page dir; one snippet is written per page found there",
    )
    args = parser.parse_args(argv)

    spec = yaml.safe_load(pathlib.Path(args.spec).read_text())
    tables = service_tables(spec, args.link_base)

    # One snippet per landing page, not per spec tag. A tag with no landing
    # page needs no snippet; a landing page whose service has no endpoints yet
    # gets the empty state, which is generated rather than written into the
    # page -- that is the thing that would otherwise go stale.
    by_slug = {mintlify_slug(label): label for label in tables}
    wanted = {
        page.stem: by_slug.get(page.stem, page.stem)
        for page in sorted(pathlib.Path(args.services_dir).glob("*.mdx"))
    }

    out_dir = pathlib.Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    written = empty = 0
    for slug, label in sorted(wanted.items()):
        body = tables.get(label) or EMPTY.format(changelog=args.changelog)
        if label not in tables:
            empty += 1
        path = out_dir / f"{slug}-endpoints.mdx"
        content = HEADER.format(body=body)
        if path.exists() and path.read_text() == content:
            continue
        path.write_text(content)
        written += 1
    print(f"{out_dir}: {len(wanted)} snippets ({empty} with no endpoints), "
          f"{written} written")
    return 0


if __name__ == "__main__":
    sys.exit(main())
