name: Build and Deploy Docs

on: 
  workflow_dispatch: # This enables manual runs. Just in case.
  push:
      branches:
      - main
      - develop
      - abhijna/algolia-improvements

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: Build for staging
        if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/abhijna/algolia-improvements'
        env:
          ALGOLIA_INDEX_NAME: docs-staging
        run: yarn build
      - name: Build for production
        if: github.ref == 'refs/heads/main'
        run: yarn build
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::338683922796:role/semgrep-docs-deploy-role
          role-duration-seconds: 900
          role-session-name: deploy
          aws-region: us-west-2
      - name: Deploy to staging
        if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/abhijna/algolia-improvements'
        run: aws s3 sync build/ s3://staging-semgrep-dev/docs --delete
      - name: Deploy to production
        if: github.ref == 'refs/heads/main'
        run: aws s3 sync build/ s3://semgrep-docs/docs --delete
