name: Check Markdown links

on: [pull_request]

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: gaurav-nelson/github-action-markdown-link-check@1
        with:
          use-verbose-mode: "yes"
          use-quiet-mode: "yes"
          base-branch: "main"
          check-modified-files-only: "yes"
          config-file: ".mlc_config.json"
