name: Check Markdown links

on:
  schedule:
    - cron: "31 23 * * 4"

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: gaurav-nelson/github-action-markdown-link-check@9710f0fec812ce0a3b98bef4c9d842fc1f39d976 # 1.0.13
        with:
          use-quiet-mode: "yes"
          use-verbose-mode: "yes"
          base-branch: "main"
          check-modified-files-only: "no"
          config-file: ".mlc_config.json"
