# Name of this GitHub Actions workflow.
name: Update semgrep help command

on:
  repository_dispatch:
    types: [new_release]
  workflow_dispatch: {}

jobs:
  update-output:
    name: Update `--help` and `--help scan` command output
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Authenticate as semgrep-autoapprover
        id: generate-token
        uses: actions/create-github-app-token@d72941d797fd3113feb6b93fd0dec494b13a2547 # v1.12.0
        with:
          app-id: ${{ vars.SEMGREP_DOCS_RELEASE_APP_ID }}
          private-key: ${{ secrets.SEMGREP_DOCS_RELEASE_PRIVATE_KEY }}

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: ${{ steps.generate-token.outputs.token }}

      - name: Resolve latest Semgrep release tag
        run: |
          LATEST_VERSION=$(gh release view -R semgrep/semgrep --json tagName -q .tagName | sed 's/^v//g')
          echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}

      - name: Run `semgrep --help` and update reference file with output
        run: |
          docker run --rm semgrep/semgrep:$LATEST_VERSION semgrep --help | sed -r 's/\x1B\[[0-9;]*[a-zA-Z]//g' | tee src/components/reference/_cli-help-output.md
          sed -i '1i```' src/components/reference/_cli-help-output.md
          echo '```' >> src/components/reference/_cli-help-output.md

      - name: Run `semgrep scan --help` and update reference file with output
        run: |
          docker run --rm semgrep/semgrep:$LATEST_VERSION semgrep scan --help | sed -r 's/\x1B\[[0-9;]*[a-zA-Z]//g' | tee src/components/reference/_cli-help-scan-output.md
          sed -i '1i```' src/components/reference/_cli-help-scan-output.md
          echo '```' >> src/components/reference/_cli-help-scan-output.md

      - name: Run `semgrep ci --help` and update reference file with output
        run: |
          docker run --rm semgrep/semgrep:$LATEST_VERSION semgrep ci --help | sed -r 's/\x1B\[[0-9;]*[a-zA-Z]//g' | tee src/components/reference/_cli-help-ci-output.md
          sed -i '1i```' src/components/reference/_cli-help-ci-output.md
          echo '```' >> src/components/reference/_cli-help-ci-output.md

      - name: Create pull request
        uses: step-security/create-pull-request@e604d57b37b404d8bb34d152fa905e45d003a895 # v8.1.0
        with:
          token: ${{ steps.generate-token.outputs.token }}
          branch: update_help_commands_${{ env.LATEST_VERSION }}
          commit-message: Updated help command output based on latest Semgrep release
          title: Update help command output for Semgrep ${{ env.LATEST_VERSION }}
          body: This is an automatically generated PR
          delete-branch: true
